config/routes.rb
BtcjamClient::Application.routes.draw do

  match 'authenticated_calls/:api' => 'api#authenticated_calls', :as => :authenticated_calls
  match 'invest_call/:api' => 'api#invest_call', :as => :invest_call
  match 'open_calls/:api' => 'api#open_calls', :as => :open_calls
  match 'new_user_calls/:api' => 'api#new_user_calls', :as => :new_user_calls
   match 'new_id_calls/:api' => 'api#new_id_calls', :as => :new_id_calls
   match 'new_addr_calls/:api' => 'api#new_addr_calls', :as => :new_addr_calls
   match 'new_credit_calls/:api' => 'api#new_credit_calls', :as => :new_credit_calls 
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    delete "/logout" => "devise/sessions#destroy"
  end

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :omniauthable

  attr_accessible :email, :alias, :oauth_data


  def self.find_or_create_for_btcjam_oauth(oauth_data)

    User.find_or_initialize_by_btcjam_uid(oauth_data.uid).tap do |user|
      user.alias = oauth_data.info.alias
      user.oauth_data = oauth_data.to_json
      user.btcjam_uid = oauth_data.uid
    end
  end

  def update_btcjam_credentials(oauth_data)

    self.btcjam_access_token = oauth_data.credentials.token
    self.oauth_data = oauth_data.to_json
  end


  def oauth_info(tag)

    JSON.parse(self.oauth_data)["info"][tag] if self.oauth_data.present?
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  include SSLAccess
  respond_to :json

  def authenticated_calls

    @json = btcjam_access_token.get("api/v1/#{params[:api]}").parsed
    render :json => @json
  end
   

  def invest_call

    @json = btcjam_access_token.post("api/v1/#{params[:api]}").parsed
    render :json => @json
  end

  def open_calls
 
    if params[:api]=='listings' 
      @listings = SSLAccess::ssl_get("#{BTCJAM_APP_URL}/api/v1/#{params[:api]}", {:appid => BTCJAM_APP_ID, :secret => BTCJAM_APP_SECRET} )
    end
	
	if params[:api]=='listingsFilter' 
      @listings = SSLAccess::ssl_get("#{BTCJAM_APP_URL}/api/v1/listings", {:appid => BTCJAM_APP_ID, :secret => BTCJAM_APP_SECRET} )
	  @json = JSON.parse(@listings.to_json)
	  @result = Array.new
	  @json.each do |listing|
		if listing["listing"]["user"]["btcjam_score"] == 'A' 
			logger.debug "hash: #{@listing.inspect}"
			@result.push(listing)
		end
	  end
      
	  
    end

    render :json => @result.to_json

  end

  def new_user_calls 
      @user = SSLAccess::ssl_post("#{BTCJAM_APP_URL}/api/v1/#{params[:api]}", :appid => BTCJAM_APP_ID, :secret => BTCJAM_APP_SECRET, 'user[email]'=>params[:username], 'user[password]'=>params[:password])
 
     render :json => @user.to_json
    
  end


  def new_id_calls
    post_hash = {  'identity_check[img_front]' => Faraday::UploadIO.new(params[:picture], 'image/jpeg'),
      'identity_check[img_back]' => Faraday::UploadIO.new(params[:picture_back], 'image/jpeg'),
      'identity_check[img_face]' => Faraday::UploadIO.new(params[:picture_face], 'image/jpeg'),
       'identity_check[name]'=>params[:name],'identity_check[dob]'=>params[:dob],'identity_check[gender]'=>params[:gender],'identity_check[nationalid]'=>params[:nationalid],'identity_check[nationalid_type_id]' => params[:nationalid_type_id]}
    @jret = client_token_multipart.request(:post, "#{BTCJAM_APP_URL}/api/v1/#{params[:api]}", { body: post_hash } ).parsed
   
    render :json => @jret
    
  end
  
  
  def new_addr_calls
    post_hash = {  'addr_check[img]' => Faraday::UploadIO.new(params[:picture], 'image/jpeg'),
       'addr_check[addr1]'=>params[:addr1],'addr_check[addr2]'=>params[:addr2],'addr_check[zip]'=>params[:zip],'addr_check[city]'=>params[:city],'addr_check[state]'=>params[:state],'addr_check[country]'=>params[:country], }
    @jret = client_token_multipart.request(:post, "#{BTCJAM_APP_URL}/api/v1/#{params[:api]}", { body: post_hash } ).parsed
    
    render :json => @jret
    
  end  
  
  
  def new_credit_calls 
    post_hash = {  'credit_check[proof_of_income_1]' => Faraday::UploadIO.new(params[:picture1], 'image/jpeg'), 
       'credit_check[ssn]'=>params[:ssn],
       'credit_check[annual_income]'=>params[:annual_income],'credit_check[employment_status_id]'=>params[:employment_status_id],'credit_check[credit_score]'=>params[:credit_score], }
    
    post_hash['credit_check[proof_of_income_2]'] = Faraday::UploadIO.new(params[:picture2], 'image/jpeg') if params[:picture2].present?
    post_hash['credit_check[proof_of_income_3]'] = Faraday::UploadIO.new(params[:picture3], 'image/jpeg') if params[:picture3].present?
   
    if !params[:car_ownership].nil?
        post_hash['credit_check[car_ownership]']='true'
    else
        post_hash['credit_check[car_ownership]']='false'
    end 
    
    if !params[:home_ownership].nil?
        post_hash['credit_check[home_ownership]']='true'
    else
        post_hash['credit_check[home_ownership]']='false'
    end  
    
    @jret = client_token_multipart.request(:post, "#{BTCJAM_APP_URL}/api/v1/#{params[:api]}", { body: post_hash } ).parsed
    
    render :json => @jret
    
  end  
  
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def btcjam_oauth_client
    @client ||= OAuth2::Client.new(BTCJAM_APP_ID, BTCJAM_APP_SECRET, :site => BTCJAM_APP_URL)
  end

  def btcjam_access_token
    @token ||= OAuth2::AccessToken.new(btcjam_oauth_client, current_user.btcjam_access_token) if current_user
  end
  
  def client_token_multipart
    OAuth2::AccessToken.new(client_multipart, current_user.btcjam_access_token)
  end
  
  def client_multipart
    OAuth2::Client.new(BTCJAM_APP_ID, BTCJAM_APP_SECRET, site: BTCJAM_APP_URL) do |builder|
      builder.use Faraday::Request::Multipart
      builder.use Faraday::Adapter::NetHttp
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index 
    if signed_in?
      
      @statuses = SSLAccess::ssl_get("#{BTCJAM_APP_URL}/employment_statuses.json" )
      @nationalid_types = SSLAccess::ssl_get("#{BTCJAM_APP_URL}/nationalid_types.json" )
      
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def btcjam
    oauth_data = request.env["omniauth.auth"]

    @user = User.find_or_create_for_btcjam_oauth(oauth_data)
    @user.update_btcjam_credentials(oauth_data)
    @user.save

    sign_in_and_redirect @user
  end

  def failure
    redirect_to root_path

  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_checks_forms.html.haml
.row
  .col-md-4
    .panel.panel-default
      .panel-heading
        .panel-title.text-center
          Identity check
      =form_tag( new_id_calls_path(:identity_checks), multipart: true) do
        .form-group.panel-body
          .row
            .col-md-4
              =label_tag "Name"
            .col-md-8
              =text_field_tag :name, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Gender"
            .col-md-8
              =text_field_tag :gender, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Date of Birth(YYYY-MM-DD)"
            .col-md-8
              =text_field_tag :dob , '',class: "form-control"
          .row
            .col-md-4
              =label_tag "National ID type"
            .col-md-8
              =select_tag :nationalid_type_id, options_for_select(@nationalid_types.collect{ |u| [ u["name"],u["id"]] }),class: "form-control"
          .row
            .col-md-4
              =label_tag "National Identification Number"
            .col-md-8
              =text_field_tag :nationalid, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Document Picture - front"
            .col-md-8
              =file_field_tag 'picture' 
          .row
            .col-md-4
              =label_tag "Document Picture - back"
            .col-md-8
              =file_field_tag 'picture_back' 
          .row
            .col-md-4
              =label_tag "Document Picture - with face"
            .col-md-8
              =file_field_tag 'picture_face' 
          %br/
          .text-center
            =submit_tag "Submit id check" , class: "btn btn-default" 
  .col-md-4
    .panel.panel-default
      .panel-heading
        .panel-title.text-center
          Address check
      =form_tag( new_addr_calls_path(:addr_checks), multipart: true) do
        .form-group.panel-body
          .row
            .col-md-4
              =label_tag "Addres line 1"
            .col-md-8
              =text_field_tag :addr1, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Addres line 2"
            .col-md-8
              =text_field_tag :addr2, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "zip code"
            .col-md-8
              =text_field_tag :zip , '',class: "form-control"
          .row
            .col-md-4
              =label_tag "City"
            .col-md-8
              =text_field_tag :city, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "State"
            .col-md-8
              =text_field_tag :state, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Country"
            .col-md-8
              =text_field_tag :country, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Proof of address Picture"
            .col-md-8
              =file_field_tag 'picture' 
          %br/
          .text-center
            =submit_tag "Submit Address check" , class: "btn btn-default"
  .col-md-4
    .panel.panel-default
      .panel-heading
        .panel-title.text-center
          Income check
      =form_tag( new_credit_calls_path(:credit_checks), multipart: true) do
        .form-group.panel-body
          .row
            .col-md-4
              =label_tag "SSN"
            .col-md-8
              =text_field_tag :ssn, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Home ownership"
            .col-md-8
              =check_box_tag :home_ownership, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Car Ownership"
            .col-md-8
              =check_box_tag :car_ownership , '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Annual Income"
            .col-md-8
              =text_field_tag :annual_income, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Employment Status"
            .col-md-8
              =select_tag :employment_status_id, options_for_select(@statuses.collect{ |u| [ u["name"],u["id"]] }),class: "form-control"
          .row
            .col-md-4
              =label_tag "Credit Score"
            .col-md-8
              =text_field_tag :credit_score, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Proof of Income 1*"
            .col-md-8
              =file_field_tag 'picture1' 
          .row
            .col-md-4
              =label_tag "Proof of Income 2"
            .col-md-8
              =file_field_tag 'picture2' 
          .row
            .col-md-4
              =label_tag "Proof of Income 3"
            .col-md-8
              =file_field_tag 'picture3' 
          %br/
          .text-center
            =submit_tag "Submit Credit check" , class: "btn btn-default"      
 
       

app/views/home/index.html.haml
%section
  .row
    .well
      .col-md-12  
        %p
          For more information please visit #{link_to "our repository", "https://github.com/btcjam/btcjam-client"} and our #{link_to "API FAQ", "https://btcjam.com/faq/api"}
          %br/
  .row
    .col-md-12
      .row
        - unless signed_in?
          .well
            .row
              .col-md-6
                .panel.panel-default
                  .panel-heading 
                    .panel-title.text-center
                      Sign in to explore the OAuth2 API  
                  .panel-body          
                    %p= link_to "Sign in with OAuth 2 provider", user_omniauth_authorize_path(:btcjam),  :class => "btn primary"
              .col-md-4.col-md-offset-2
                .panel.panel-default
                  .panel-heading 
                    .panel-title.text-center
                      Don't have an account? Create it!
                  .form-group.panel-body
           
                    =form_tag( new_user_calls_path(:users)) do
                      .row
                        .col-md-4
                          =label_tag "Username"
                        .col-md-8
                          =text_field_tag :username , '',class: "form-control"
                        .col-md-4
                          =label_tag "Password"
                        .col-md-8
                          =password_field_tag :password ,'',class: "form-control"
                        %br/
                        %br/
                        .col-md-12.text-center
                          =submit_tag "Create User" , class: "btn btn-default" 
          %br/ 
        - else
          %h2 BTCJam OAuth2 API
          .well 
            %p
              You are logged in as: <strong>#{current_user.oauth_info("alias")}</strong>
              %ul 
                %li BTCJam score: <strong>#{current_user.oauth_info("btcjam_score")}</strong> 
            %p
              = link_to "User Information", authenticated_calls_path(:me), :class => "btn", "data-explore" => []
              = link_to "My Open Listings", authenticated_calls_path(:my_open_listings), :class => "btn", "data-explore" => []
              = link_to "My Receivables", authenticated_calls_path(:my_receivables), :class => "btn", "data-explore" => []
              = link_to "My Payables", authenticated_calls_path(:my_payables), :class => "btn", "data-explore" => []
              = link_to "Invest", invest_call_path(:investments, {:listing_id => 1, :amount => 0.1}), :class => "btn", "data-explore" => []
              = link_to "Sign out", "/logout", :class => "btn primary", :method => :delete 
            %br/
            %p
              = link_to "My ID Checks", authenticated_calls_path(:identity_checks), :class => "btn", "data-explore" => []
              = link_to "My Address Checks", authenticated_calls_path(:addr_checks), :class => "btn", "data-explore" => []
              = link_to "My Credit Checks", authenticated_calls_path(:credit_checks), :class => "btn", "data-explore" => []
            .row 
              .col-md-12
                %h3.text-center
                  Submit your documents via API
            = render partial: 'checks_forms'

    .col-md-12
      %h2 BTCJam JSON API
      .well
        %table.table.table-striped.table-bordered
          %thead
            %tr

              %th Request Format
          %tbody
            %tr

              %td https://btcjam.com/api/v1/listings?appid=[<strong>APP ID</strong>]&secret=[<strong>APP Secret</strong>]

        %p
        = link_to "Query All Open Listings", open_calls_path(:listings), :class => "btn", "data-explore" => []
        = link_to "Query All Open Listings", open_calls_path(:listingsFilter), :class => "btn", "data-explore" => []
        %br/
        %br/
        %br/


  .row
    .col-md-12
      %p
        %pre#display-json
          Select one of the api methods above
:javascript
  $( document ).ready(function() {
   populateLists("#{BTCJAM_APP_URL}",'listings', "#{BTCJAM_APP_ID}", "#{BTCJAM_APP_SECRET}")
  });

app/views/layouts/application.html.haml
!!! 5
%html
  %head

    %title BTCJAM API Demo
    = stylesheet_link_tag    "https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
    = stylesheet_link_tag    "application"
    = csrf_meta_tags
    - if Rails.env.production?
      :javascript
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-34687829-2', 'herokuapp.com');
        ga('send', 'pageview');

  %body
    .topbar
      .fill
        .container
          = link_to "BTCJAM API Demo", root_path, :class => "brand"
    = javascript_include_tag "application"
    = javascript_include_tag "http://twitter.github.com/bootstrap/1.4.0/bootstrap-buttons.min.js"
    .container
      = yield